[versions]
agp = "8.7.3"
androidxJunit = "1.2.1"
converterGson = "2.1.0"
espressoCoreVersion = "3.6.1"
gson = "2.6.2"
json = "20210307"
jsoup = "1.15.3"
kotlin = "1.9.24"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
materialSpinner = "1.3.1"
navigationFragmentKtx = "2.6.0"
navigationUiKtx = "2.6.0"
khttp = "0.1.0"
opencvAndroidVersion = "4.5.1"
retrofit = "2.1.0"
retrofitVersion = "2.9.0"
compiler = "3.2.0-alpha11"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core-v361 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-junit-v121 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
json = { module = "org.json:json", version.ref = "json" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
khttp = { group = "com.github.jkcclemens", name = "khttp", version.ref = "khttp" }
material-spinner = { module = "com.jaredrummler:material-spinner", version.ref = "materialSpinner" }
opencv-opencv-android = { module = "org.opencv:opencv-android", version.ref = "opencvAndroidVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-v290 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
androidx-compiler = { group = "androidx.databinding", name = "compiler", version.ref = "compiler" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

